name: Update stations' csv

on:
  push:
    branches: ['main']
  schedule:
    # at 8pm on Sundays
    - cron: "0 20 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Set up poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: '1.1.12'

    - name: Run the data fetch python script
      run: |
        poetry install
        poetry run python main.py

    - name: Commit files
      run: |
        git config --local user.name "Michal Ziemski"
        git add ./stations/stations.csv
        git commit -m "Update the list of PubliBike stations"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: false
